apiVersion: skaffold/v1
kind: Config
metadata:
  name: monitoring-api
deploy:
  kubectl:
    manifests:
    - k8s/monitoring-api.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/monitoring-api
  local: {}
